[project]
name = "code-patterns-with-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.29.5",
    "marimo[recommended]>=0.12.8",
    "watchdog>=6.0.0",
]
